name: Go Tests

on:
  pull_request:
    branches:
      - main
  workflow_call:
    outputs:
      test-result:
        description: "Test execution result"
        value: ${{ jobs.test.outputs.result }}

jobs:
  test:
    name: Run Go Tests
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.test-step.outputs.result }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "^1.24"
          check-latest: true

      - name: Get dependencies
        run: go mod tidy

      - name: Run tests
        id: test-step
        run: |
          go test -v -race ./...
          echo "result=success" >> $GITHUB_OUTPUT